/**
 * APP PROPS
 * 
 * Hook que crea un objeto con todas las props para los componentes
 */

export const useAppProps = ({
  fileInputRef,
  handleImageUploadWrapper,
  addTextLayerWrapper,
  addCircleLayerWrapper,
  addSquareLayerWrapper,
  addLineLayerWrapper,
  addGradientLayerWrapper,
  setShowMoreOptions,
  setAspectRatioMenu,
  setFileMenu,
  setEmojiPicker,
  zoomLevel,
  setZoomLevel,
  setPanOffset,
  showMoreOptions,
  aspectRatio,
  aspectRatios,
  aspectRatioMenu,
  setAspectRatio,
  handleTitleClick,
  canvasRef,
  currentRatio,
  panOffset,
  handleMouseDown,
  handleMouseMove,
  handleMouseUp,
  handleContextMenu,
  handleDoubleClick,
  selectedLayer,
  selectedLayerId,
  layers,
  setLayers,
  transformPanel,
  setTransformPanel,
  layersCollapsed,
  setLayersCollapsed,
  transformCollapsed,
  setTransformCollapsed,
  adjustmentPanel,
  setAdjustmentPanel,
  adjustmentCollapsed,
  setAdjustmentCollapsed,
  resetConfirmModal,
  setResetConfirmModal,
  autoShowTransform,
  setAutoShowTransform,
  autoShowAdjustment,
  setAutoShowAdjustment,
  contextMenu,
  setContextMenu,
  resetLayerTransformations,
  deleteLayerWrapper,
  moveLayerWrapper,
  toggleLayerVisibilityWrapper,
  updateLayerOpacityWrapper,
  setSelectedLayerId
}) => {
  const leftSidebarProps = {
    fileInputRef,
    handleImageUploadWrapper,
    addTextLayerWrapper,
    addCircleLayerWrapper,
    addSquareLayerWrapper,
    addLineLayerWrapper,
    addGradientLayerWrapper,
    setShowMoreOptions,
    setAspectRatioMenu,
    setFileMenu,
    setEmojiPicker,
    zoomLevel,
    setZoomLevel,
    setPanOffset,
    panOffset,
    showMoreOptions,
    aspectRatio,
    aspectRatios,
    aspectRatioMenu,
    setAspectRatio,
    currentRatio
  }

  const mainContentProps = {
    handleTitleClick,
    canvasRef,
    currentRatio,
    zoomLevel,
    panOffset,
    handleMouseDown,
    handleMouseMove,
    handleMouseUp,
    handleContextMenu,
    handleDoubleClick,
    selectedLayer,
    selectedLayerId,
    layers,
    setLayers,
    transformPanel,
    setTransformPanel,
    layersCollapsed,
    setLayersCollapsed,
    transformCollapsed,
    setTransformCollapsed,
    adjustmentPanel,
    setAdjustmentPanel,
    adjustmentCollapsed,
    setAdjustmentCollapsed,
    resetConfirmModal,
    setResetConfirmModal,
    autoShowTransform,
    setAutoShowTransform,
    autoShowAdjustment,
    setAutoShowAdjustment,
    contextMenu,
    setContextMenu,
    resetLayerTransformations,
    deleteLayer: deleteLayerWrapper,
    moveLayer: moveLayerWrapper,
    toggleLayerVisibility: toggleLayerVisibilityWrapper,
    updateLayerOpacity: updateLayerOpacityWrapper,
    setSelectedLayerId
  }

  return {
    leftSidebarProps,
    mainContentProps
  }
}
